// GENERATED_HASH: 8f95a50cd519c592
#ifndef _MAIN_PAGE_H_
#define _MAIN_PAGE_H_

// ===== Auto-generated by EmbeddedGUI Designer =====
// This file is regenerated when the layout changes.
// Extend the page via the user-owned main_page_ext.h and main_page.c files.

#include "egui.h"

typedef struct egui_main_page egui_main_page_t;
#include "main_page_ext.h"

#ifndef EGUI_MAIN_PAGE_EXT_FIELDS
#define EGUI_MAIN_PAGE_EXT_FIELDS
#endif

#ifndef EGUI_MAIN_PAGE_HOOK_INIT
#define EGUI_MAIN_PAGE_HOOK_INIT(_page) egui_main_page_user_init(_page)
#endif
#ifndef EGUI_MAIN_PAGE_HOOK_ON_OPEN
#define EGUI_MAIN_PAGE_HOOK_ON_OPEN(_page) egui_main_page_user_on_open(_page)
#endif
#ifndef EGUI_MAIN_PAGE_HOOK_ON_CLOSE
#define EGUI_MAIN_PAGE_HOOK_ON_CLOSE(_page) egui_main_page_user_on_close(_page)
#endif
#ifndef EGUI_MAIN_PAGE_HOOK_ON_KEY
#define EGUI_MAIN_PAGE_HOOK_ON_KEY(_page, _keycode) egui_main_page_user_on_key_pressed(_page, _keycode)
#endif

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

void egui_main_page_user_init(egui_main_page_t *page);
void egui_main_page_user_on_open(egui_main_page_t *page);
void egui_main_page_user_on_close(egui_main_page_t *page);
void egui_main_page_user_on_key_pressed(egui_main_page_t *page, uint16_t keycode);

struct egui_main_page
{
    egui_page_base_t base;

    // UI widgets (auto-generated, do not edit)
    egui_view_group_t root_group;
    egui_view_label_t hello_label;
    egui_view_button_t hello_btn;

    EGUI_MAIN_PAGE_EXT_FIELDS
};

// Layout init (auto-generated in .designer/main_page_layout.c)
void egui_main_page_layout_init(egui_page_base_t *self);

// Page init (auto-generated in .designer/main_page_layout.c)
void egui_main_page_init(egui_page_base_t *self);

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _MAIN_PAGE_H_ */
