// GENERATED_HASH: edf52521ce4d220b
// ===== Auto-generated by EmbeddedGUI Designer =====
// DO NOT EDIT – this file is fully regenerated on every save.
// User logic belongs in main_page.c and main_page_ext.h (never overwritten).

#include "egui.h"
#include <stdlib.h>

#include "uicode.h"
#include "main_page.h"

void egui_main_page_layout_init(egui_page_base_t *self)
{
    egui_main_page_t *local = (egui_main_page_t *)self;

    // Init views
    // root_group (group)
    egui_view_group_init((egui_view_t *)&local->root_group);
    egui_view_set_position((egui_view_t *)&local->root_group, 0, 0);
    egui_view_set_size((egui_view_t *)&local->root_group, 240, 320);

    // hello_label (label)
    egui_view_label_init((egui_view_t *)&local->hello_label);
    egui_view_set_position((egui_view_t *)&local->hello_label, 20, 96);
    egui_view_set_size((egui_view_t *)&local->hello_label, 200, 32);
    egui_view_label_set_text((egui_view_t *)&local->hello_label, "Hello EmbeddedGUI");
    egui_view_label_set_font((egui_view_t *)&local->hello_label, (egui_font_t *)EGUI_CONFIG_FONT_DEFAULT);
    egui_view_label_set_font_color((egui_view_t *)&local->hello_label, EGUI_COLOR_WHITE, EGUI_ALPHA_100);

    // hello_btn (button)
    egui_view_button_init((egui_view_t *)&local->hello_btn);
    egui_view_set_position((egui_view_t *)&local->hello_btn, 60, 156);
    egui_view_set_size((egui_view_t *)&local->hello_btn, 120, 40);
    egui_view_label_set_text((egui_view_t *)&local->hello_btn, "HelloSimple");
    egui_view_label_set_font((egui_view_t *)&local->hello_btn, (egui_font_t *)EGUI_CONFIG_FONT_DEFAULT);
    egui_view_label_set_font_color((egui_view_t *)&local->hello_btn, EGUI_COLOR_BLACK, EGUI_ALPHA_100);

    // Build hierarchy
    egui_view_group_add_child((egui_view_t *)&local->root_group, (egui_view_t *)&local->hello_label);
    egui_view_group_add_child((egui_view_t *)&local->root_group, (egui_view_t *)&local->hello_btn);

    // Add to page root
    egui_page_base_add_view(self, (egui_view_t *)&local->root_group);

}

static void egui_main_page_on_open(egui_page_base_t *self)
{
    egui_main_page_t *local = (egui_main_page_t *)self;
    EGUI_UNUSED(local);
    egui_page_base_on_open(self);
    egui_main_page_layout_init(self);
    EGUI_MAIN_PAGE_HOOK_ON_OPEN(local);
}

static void egui_main_page_on_close(egui_page_base_t *self)
{
    egui_main_page_t *local = (egui_main_page_t *)self;
    EGUI_UNUSED(local);
    egui_page_base_on_close(self);
    EGUI_MAIN_PAGE_HOOK_ON_CLOSE(local);
}

static void egui_main_page_on_key_pressed(egui_page_base_t *self, uint16_t keycode)
{
    egui_main_page_t *local = (egui_main_page_t *)self;
    EGUI_UNUSED(local);
    EGUI_UNUSED(keycode);
    EGUI_MAIN_PAGE_HOOK_ON_KEY(local, keycode);
}

static const egui_page_base_api_t EGUI_VIEW_API_TABLE_NAME(egui_main_page_t) = {
    .on_open = egui_main_page_on_open,
    .on_close = egui_main_page_on_close,
    .on_key_pressed = egui_main_page_on_key_pressed,
};

void egui_main_page_init(egui_page_base_t *self)
{
    egui_main_page_t *local = (egui_main_page_t *)self;
    EGUI_UNUSED(local);
    egui_page_base_init(self);
    self->api = &EGUI_VIEW_API_TABLE_NAME(egui_main_page_t);
    egui_page_base_set_name(self, "main_page");
    EGUI_MAIN_PAGE_HOOK_INIT(local);
}
