#ifndef _MAIN_PAGE_H_
#define _MAIN_PAGE_H_

// ===== Auto-generated by EmbeddedGUI Designer =====
// This file is regenerated when the layout changes.
// Only the USER CODE regions are preserved.

#include "egui.h"
#include "widgets/egui_view_fallback_pill.h"

// USER CODE BEGIN includes
// USER CODE END includes
/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

typedef struct egui_main_page egui_main_page_t;
struct egui_main_page
{
    egui_page_base_t base;

    // UI widgets (auto-generated, do not edit)
    egui_view_group_t root_group;
    egui_view_label_t title_label;
    egui_view_fallback_pill_t status_badge;

    // USER CODE BEGIN user_fields
    // USER CODE END user_fields
};

// Layout init (auto-generated in main_page_layout.c)
void egui_main_page_layout_init(egui_page_base_t *self);

// Page init (user-implemented in main_page.c)
void egui_main_page_init(egui_page_base_t *self);

// USER CODE BEGIN declarations
// USER CODE END declarations
/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _MAIN_PAGE_H_ */
