// GENERATED_HASH: 86f8bbe51fc5749a
// ===== Auto-generated by EmbeddedGUI Designer =====
// DO NOT EDIT — this file is fully regenerated on every save.
// User logic belongs in main_page.c (never overwritten).

#include "egui.h"
#include <stdlib.h>

#include "uicode.h"
#include "main_page.h"

void egui_main_page_layout_init(egui_page_base_t *self)
{
    egui_main_page_t *local = (egui_main_page_t *)self;

    // Init views
    // root_group (group)
    egui_view_group_init((egui_view_t *)&local->root_group);
    egui_view_set_position((egui_view_t *)&local->root_group, 0, 0);
    egui_view_set_size((egui_view_t *)&local->root_group, 240, 320);

    // title_label (label)
    egui_view_label_init((egui_view_t *)&local->title_label);
    egui_view_set_position((egui_view_t *)&local->title_label, 24, 86);
    egui_view_set_size((egui_view_t *)&local->title_label, 192, 34);
    egui_view_label_set_text((egui_view_t *)&local->title_label, "Python descriptor fallback");
    egui_view_label_set_font((egui_view_t *)&local->title_label, (egui_font_t *)EGUI_CONFIG_FONT_DEFAULT);
    egui_view_label_set_font_color((egui_view_t *)&local->title_label, EGUI_COLOR_WHITE, EGUI_ALPHA_100);

    // status_badge (fallback_pill)
    egui_view_fallback_pill_init((egui_view_t *)&local->status_badge);
    egui_view_set_position((egui_view_t *)&local->status_badge, 44, 148);
    egui_view_set_size((egui_view_t *)&local->status_badge, 152, 36);
    egui_view_fallback_pill_set_text((egui_view_t *)&local->status_badge, "Manual widget active");
    egui_view_fallback_pill_set_emphasis((egui_view_t *)&local->status_badge, 1);

    // Build hierarchy
    egui_view_group_add_child((egui_view_t *)&local->root_group, (egui_view_t *)&local->title_label);
    egui_view_group_add_child((egui_view_t *)&local->root_group, (egui_view_t *)&local->status_badge);

    // Add to page root
    egui_page_base_add_view(self, (egui_view_t *)&local->root_group);

}
