// ===== Auto-generated by EmbeddedGUI Designer =====

#include "egui.h"
#include <stdlib.h>
#include "uicode.h"

#include "main_page.h"

static egui_toast_std_t toast;
static egui_page_base_t *current_page = NULL;

union page_array {
    egui_main_page_t main_page;
};

static union page_array g_page_array;
static int current_index = 0;
static char toast_str[50];

void uicode_switch_page(int page_index)
{
    current_index = page_index;

    egui_api_sprintf(toast_str, "Start page %d", page_index);
    egui_core_toast_show_info(toast_str);

    if (current_page)
    {
        egui_page_base_close(current_page);
    }

    switch (page_index)
    {
    case 0:
        egui_main_page_init((egui_page_base_t *)&g_page_array.main_page);
        current_page = (egui_page_base_t *)&g_page_array.main_page;
        break;
    default:
        break;
    }

    egui_page_base_open(current_page);
}

int uicode_start_next_page(void)
{
    int page_index = current_index + 1;
    if (page_index >= PAGE_COUNT)
    {
        egui_core_toast_show_info("No more next page");
        return -1;
    }

    uicode_switch_page(page_index);
    return 0;
}

int uicode_start_prev_page(void)
{
    int page_index = current_index - 1;
    if (page_index < 0)
    {
        egui_core_toast_show_info("No more previous page");
        return -1;
    }

    uicode_switch_page(page_index);
    return 0;
}

void egui_port_hanlde_key_event(int key, int event)
{
    if (event == 0)
    {
        return;
    }

    if (current_page)
    {
        egui_page_base_key_pressed(current_page, key);
    }
}

void uicode_init_ui(void)
{
    // Start with startup page
    current_index = 0;
    uicode_switch_page(0);

    // Init toast
    egui_toast_std_init((egui_toast_t *)&toast);
    egui_core_toast_set((egui_toast_t *)&toast);
}

void uicode_create_ui(void)
{
    uicode_init_ui();
}
